package com.huseyinaydin;
// Generated 01.Ara.2016 18:40:35 by Hibernate Tools 5.2.0.Beta1

/**
 * Adres generated by hbm2java
 */
public class Adres implements java.io.Serializable {

	private String cadde;
	private String sehir;
	private String sokak;
	private String postaKodu;

	public Adres() {
	}

	public Adres(String cadde, String sehir, String sokak, String postaKodu) {
		this.cadde = cadde;
		this.sehir = sehir;
		this.sokak = sokak;
		this.postaKodu = postaKodu;
	}

	public String getCadde() {
		return this.cadde;
	}

	public void setCadde(String cadde) {
		this.cadde = cadde;
	}

	public String getSehir() {
		return this.sehir;
	}

	public void setSehir(String sehir) {
		this.sehir = sehir;
	}

	public String getSokak() {
		return this.sokak;
	}

	public void setSokak(String sokak) {
		this.sokak = sokak;
	}

	public String getPostaKodu() {
		return this.postaKodu;
	}

	public void setPostaKodu(String postaKodu) {
		this.postaKodu = postaKodu;
	}

}
