package com.huseyinaydin;
// Generated 01.Ara.2016 18:40:35 by Hibernate Tools 5.2.0.Beta1

/**
 * Ogrenci generated by hbm2java
 */
public class Ogrenci implements java.io.Serializable {

	private long ogrenciId;
	private String ogrenciAdi;
	private Adres adres;

	public Ogrenci() {
	}

	public Ogrenci(String ogrenciAdi, Adres adres) {
		this.ogrenciAdi = ogrenciAdi;
		this.adres = adres;
	}

	public long getOgrenciId() {
		return this.ogrenciId;
	}

	public void setOgrenciId(long ogrenciId) {
		this.ogrenciId = ogrenciId;
	}

	public String getOgrenciAdi() {
		return this.ogrenciAdi;
	}

	public void setOgrenciAdi(String ogrenciAdi) {
		this.ogrenciAdi = ogrenciAdi;
	}

	public Adres getAdres() {
		return this.adres;
	}

	public void setAdres(Adres adres) {
		this.adres = adres;
	}

}
